from openpyxl import load_workbook
import re
from collections import defaultdict

# Base descriptions for each ANSI code
ANSI_BASE = {
    20: "PROTECAO DIFERENCIAL DE CORRENTE",
    21: "RELE DE DISTANCIA (IMPEDANCIA)",
    24: "RELE DE SOBRECORRENTE COM RESET DE SOBRECARGA",
    25: "RELE DE SINCRONISMO OU VERIFICACAO DE SINCRONISMO",
    26: "PROTECAO TERMICA DE EQUIPAMENTO",
    27: "RELE DE SUBTENSAO",
    32: "RELE DE POTENCIA DIRECIONAL",
    43: "RELE DE TRANSFERENCIA MANUAL OU SELETOR",
    46: "RELE DE SEQUENCIA REVERSA OU DESBALANCO DE FASE",
    49: "RELE TERMICO",
    50: "RELE DE SOBRECORRENTE INSTANTANEA",
    51: "RELE DE TEMPO INVERSO COM SOBRECORRENTE AC",
    59: "RELE DE SOBRETENSAO",
    61: "RELE DE RETORNO DE POTENCIA OU POTENCIA REVERSA",
    62: "RELE DE ATRASO DE PARADA OU DESLIGAMENTO",
    63: "RELE DE PRESSAO",
    67: "RELE DE SOBRECORRENTE DIRECIONAL AC",
    71: "RELE DE NIVEL DE LIQUIDO OU GAS",
    78: "RELE DE MEDICAO DE ANGULO DE FASE",
    79: "RELE DE RELIGA AUTOMATICA AC",
    81: "RELE DE FREQUENCIA",
    85: "RELE DE PORTADORA OU FIO PILOTO",
    86: "RELE DE BLOQUEIO (TRIP-FREE)",
    87: "RELE DE PROTECAO DIFERENCIAL",
    90: "DISPOSITIVO REGULADOR",
    94: "RELE DE DISPARO OU DISPARO LIVRE"
}

# Suffix meanings - adds distinction to same-base-code signals
SUFFIX_MEANINGS = {
    'F': 'FASE',
    'FA': 'FASE A',
    'FB': 'FASE B',
    'FC': 'FASE C',
    'FN': 'FASE-NEUTRO',
    'F1': 'FASE 1',
    'F2': 'FASE 2',
    'F3': 'FASE 3',
    'F4': 'FASE 4',
    'N': 'NEUTRO',
    'N1': 'NEUTRO ZONA 1',
    'N2': 'NEUTRO ZONA 2',
    'N3': 'NEUTRO ZONA 3',
    'N4': 'NEUTRO ZONA 4',
    'NL': 'NEUTRO COM BLOQUEIO',
    'Z1': 'ZONA 1',
    'Z2': 'ZONA 2',
    'Z3': 'ZONA 3',
    'Z4': 'ZONA 4',
    'Z5': 'ZONA 5',
    'D': 'DIRECIONAL',
    'EF': 'ENTRADA FALHA',
    'EM': 'ENTRADA MULTIPLA',
    'E1': 'ESTAGIO 1',
    'E2': 'ESTAGIO 2',
    'E3': 'ESTAGIO 3',
    'E4': 'ESTAGIO 4',
    'E5': 'ESTAGIO 5',
    'T': 'TEMPO',
    'T1': 'TEMPO 1',
    'T2': 'TEMPO 2',
    'TA': 'TEMPO A',
    'TC': 'TEMPO C',
    'TD': 'TEMPO DIFERENCIAL',
    'A': 'FASE A',
    'B': 'FASE B',
    'C': 'FASE C',
    'CA': 'CORRENTE AUXILIAR',
    'CD': 'CORRENTE DIFERENCIAL',
    'BF': 'BLOQUEIO FALHA DISJUNTOR',
    'I': 'INTENSIDADE',
    'I1': 'INTENSIDADE 1',
    'I2': 'INTENSIDADE 2',
    'V': 'TENSAO',
    'VT': 'VERIFICACAO TENSAO',
    'AM': 'ALIMENTACAO MULTIPLA',
    'AT': 'ALIMENTACAO TESTE',
    'ER': 'EFEITO REVERSO',
    'FT': 'FALHA TESTE',
    'IE': 'IMPEDANCIA ENTRADA',
    'LR': 'LIMITE REVERSO',
    'OK': 'CONFIRMACAO',
    'AB': 'ABERTURA',
    'AC': 'FECHAMENTO',
    'BC': 'BLOQUEIO CHAVEAMENTO',
    'BL': 'BLOQUEIO',
    'BR': 'BLOQUEIO REVERSO',
    'CC': 'CHAVEAMENTO COMANDO',
    'AB': 'ABERTURA',
    'E1': 'ESTAGIO 1',
    'E2': 'ESTAGIO 2',
    'LT': 'LIMITE TEMPO',
    'TP': 'TIPO',
    'EP': 'ENTRADA PRIMARIA',
    'RT': 'RETORNO',
    'TC': 'TRANSFERENCIA COMANDO',
    'TR': 'TRANSFERENCIA',
    'VF': 'VERIFICACAO FALHA',
    'FT': 'FALHA TESTE',
    'FR': 'FALHA REVERSO',
    'FTD': 'FALHA TESTE DIRECIONAL',
    'FTR': 'FALHA TESTE REVERSO',
    'ND': 'NEUTRO DIRECIONAL',
    'NR': 'NEUTRO REVERSO',
    'NT': 'NEUTRO TEMPO',
    'NT1': 'NEUTRO TEMPO 1',
    'NT2': 'NEUTRO TEMPO 2',
    'NTD': 'NEUTRO TEMPO DIRECIONAL',
    'NTR': 'NEUTRO TEMPO REVERSO',
    'NX': 'NEUTRO AUXILIAR',
    'P1': 'PILOT 1',
    'P2': 'PILOT 2',
    'CH': 'CHEIA',
    'CL': 'LIMITE CHEIA',
    'H': 'ALTO',
    'HI': 'LIMITE ALTO',
    'L': 'BAIXO',
    'LO': 'LIMITE BAIXO',
    'TH': 'TEMPO ALTO',
    'TL': 'TEMPO BAIXO',
    'VS': 'VERIFICACAO STATUS',
    'RE': 'RELIGA EXCLUIDA',
    'TF': 'TESTE FALHA',
    'INC': 'INCIDENTE',
    'EXC': 'EXCLUIDA',
    'AJST': 'AJUSTE',
    'IE1': 'IMPEDANCIA ENTRADA 1',
    'IE2': 'IMPEDANCIA ENTRADA 2',
    'O1': 'SOBRE FREQUENCIA 1',
    'O2': 'SOBRE FREQUENCIA 2',
    'SO': 'SOBRE',
    'SU': 'SUB',
    'U1': 'SUB FREQUENCIA 1',
    'U2': 'SUB FREQUENCIA 2',
    'U3': 'SUB FREQUENCIA 3',
    'U4': 'SUB FREQUENCIA 4',
    'U5': 'SUB FREQUENCIA 5',
    'CC': 'COMANDO CHAVEAMENTO',
    'FL': 'FALHA LOCK',
    'BL': 'BLOQUEIO',
    'EF': 'ENTRADA FALHA',
    'G': 'GERADOR',
    'LT': 'LIMITE TEMPO',
    'Q': 'QUADRANTE',
    'Q1': 'QUADRANTE 1',
    'Q2': 'QUADRANTE 2',
    'R': 'RECEPTOR',
    'R1': 'RECEPTOR 1',
    'R2': 'RECEPTOR 2',
    'RA': 'RECEPTOR A',
    'RB': 'RECEPTOR B',
    'RC': 'RECEPTOR C',
    'TA': 'TEMPO A',
    'TB': 'TEMPO B',
    'TC': 'TEMPO C',
    'TT': 'TEMPO TEMPO',
    'U1': 'UNIDADE 1',
    'U2': 'UNIDADE 2',
    'DP': 'DISPOSITIVO PRIMARIO',
    'FU': 'FUSIVEL',
    'V': 'TENSAO',
    'VF': 'VERIFICACAO FALHA',
}

# Load workbook
wb = load_workbook('docs/Pontos Padrao ADMS_v3.xlsx')
ws = wb['DiscreteSignals']

# Track which base codes got K column updates
base_code_updated_K = set()

# Iterate through rows
for row in range(2, ws.max_row + 1):
    cell_a = ws.cell(row, 1).value

    if cell_a is None or cell_a == 'CMDE':
        continue

    sinal_str = str(cell_a).strip()

    # Extract base code and suffix
    match = re.match(r'(\d{2})(.*)', sinal_str)
    if not match:
        continue

    base_code = int(match.group(1))
    suffix = match.group(2)

    # Skip if no mapping for this base code
    if base_code not in ANSI_BASE:
        continue

    # Build description with suffix if present
    base_desc = ANSI_BASE[base_code]

    if suffix:
        suffix_desc = SUFFIX_MEANINGS.get(suffix, suffix)
        desc_b = f"{base_code} - {base_desc} ({suffix_desc})"
    else:
        desc_b = f"{base_code} - {base_desc}"

    # Update column B (always uppercase)
    ws.cell(row, 2).value = desc_b

    # Update column K (Funcionamento) only for first occurrence of each base code
    if base_code not in base_code_updated_K:
        # Get functional description (same as before, in uppercase)
        func_descriptions = {
            20: "PROTECAO DIFERENCIAL QUE MONITORA A DIFERENCA ENTRE CORRENTES DE ENTRADA E SAIDA EM TRANSFORMADORES E GERADORES. DETECTA FALHAS INTERNAS COMPARANDO CORRENTES NOS TERMINAIS DE UM EQUIPAMENTO.",
            21: "PROTECAO DE LINHAS DE TRANSMISSAO BASEADA EM MEDICAO DE IMPEDANCIA/DISTANCIA. OPERA POR ZONAS DE PROTECAO E OFERECE PROTECAO ESCALONADA. SENSIVEL A VARIACOES DE IMPEDANCIA DA LINHA.",
            24: "PROTECAO DE SOBRECORRENTE COM CAPACIDADE DE RESET (RESETABLE). MONITORA CORRENTE CONTINUA E OFERECE PROTECAO CONTRA SOBRECARGAS COM MECANISMO DE REINICIALIZACAO AUTOMATICA.",
            25: "SUPERVISIONA SINCRONISMO ENTRE SISTEMA E MAQUINA SINCRONA. CONTROLA CONDICOES DE ACOPLAMENTO PARA EVITAR CONEXAO FORA DE FASE. MONITORA ANGULO, MAGNITUDE E FREQUENCIA.",
            26: "MONITORA TEMPERATURA DE EQUIPAMENTOS COMO TRANSFORMADORES E GERADORES. DETECTA CONDICOES DE SOBRETEMPERATURA USANDO SENSORES TERMICOS OU MODELOS DE ELEVACAO DE TEMPERATURA.",
            27: "MONITORA TENSAO DA REDE E OPERA QUANDO ESSA CAI ABAIXO DE VALOR PRE-AJUSTADO. PROTECAO CONTRA PERDA DE TENSAO E DESCONEXAO DE CIRCUITOS EM CONDICOES ANORMAIS.",
            32: "MONITORA FLUXO DE POTENCIA ATIVA EM UMA DIRECAO ESPECIFICA. PROTECAO CONTRA FLUXO REVERSO EM GERADORES E ALIMENTADORES. SENSIVEL A MAGNITUDE E DIRECAO DA POTENCIA.",
            43: "CONTROLA TRANSFERENCIA MANUAL ENTRE FONTES DE ALIMENTACAO. UTILIZADO EM OPERACOES DE CHAVEAMENTO E SELECAO DE CIRCUITOS POR COMANDO DO OPERADOR.",
            46: "DETECTA SEQUENCIA REVERSA DE FASES (RST EM VEZ DE STR) OU DESBALANCO ENTRE FASES. PROTECAO PARA MOTORES E EQUIPAMENTOS SENSIVEIS A SEQUENCIA DE FASES.",
            49: "PROTECAO TERMICA DOS ENROLAMENTOS DE MAQUINAS. MONITORA TEMPERATURA CALCULADA OU MEDIDA E LIMITA TEMPO DE FUNCIONAMENTO EM CONDICOES DE SOBRECARGA TERMICA.",
            50: "DETECTA SOBRECORRENTE COM OPERACAO IMEDIATA (SEM ATRASO DE TEMPO). PROTECAO DE ALTA VELOCIDADE CONTRA CURTOS-CIRCUITOS. USADO PARA PROTECAO PRIMARIA RAPIDA DE CIRCUITOS.",
            51: "PROTECAO DE SOBRECORRENTE COM CARACTERISTICA DE TEMPO INVERSO. ATRASO DE TEMPO DEPENDE DA MAGNITUDE DA CORRENTE. PROTECAO COORDENADA EM CASCATA COM RELES DOWNSTREAM.",
            59: "MONITORA TENSAO DA REDE E OPERA QUANDO ESSA ULTRAPASSA VALOR PRE-AJUSTADO. PROTECAO CONTRA SOBRETENSAO E CONEXAO INDEVIDA DE CIRCUITOS EM CONDICOES ANORMAIS.",
            61: "DETECTA INVERSAO DE FLUXO DE POTENCIA ATIVA. PROTECAO DE GERADORES CONTRA POTENCIA REVERSA INDICANDO PERDA DE ATUACAO OU FALHA DE MAQUINA MOTRIZ.",
            62: "FORNECE ATRASO DE TEMPO PROGRAMAVEL PARA OPERACOES DE PARADA OU DESLIGAMENTO. CONTROLA SEQUENCIA TEMPORIZADAS DE EVENTOS DE PROTECAO.",
            63: "MONITORA PRESSAO DE GASES OU LIQUIDOS EM EQUIPAMENTOS (EX: TRANSFORMADORES COM CONSERVADOR). PROTECAO CONTRA AUMENTO ANORMAL DE PRESSAO INDICANDO FALHAS INTERNAS.",
            67: "PROTECAO DE SOBRECORRENTE DIRECCIONADA QUE OPERA APENAS PARA CORRENTES ACIMA DO AJUSTE EM DIRECAO ESPECIFICA. PERMITE COORDENACAO BIDIRECIONAL EM MALHAS DE DISTRIBUICAO.",
            71: "MONITORA NIVEL DE LIQUIDO OU GAS EM RESERVATORIOS E CONSERVADORES DE EQUIPAMENTOS. ALERTA OU DESLIGA EQUIPAMENTOS QUANDO NIVEL ESTA FORA DOS LIMITES NORMAIS.",
            78: "MEDE E SUPERVISIONA ANGULO DE FASE ENTRE TENSOES OU CORRENTES. PROTECAO CONTRA DESVIOS DE FASE E DESINCRONISMO. USADO EM SISTEMAS DE PROTECAO DE ESTABILIDADE.",
            79: "COMANDA RELIGAMENTO AUTOMATICO APOS OPERACAO DE PROTECAO. RESTAURA CIRCUITO APOS FALHAS TRANSITORIAS. INCLUI ATRASOS E CONTADORES DE CICLOS DE RELIGA.",
            81: "MONITORA FREQUENCIA DA REDE. DETECTA SUB/SOBREFREQUENCIA INDICANDO DESBALANCEAMENTO GERADOR-CARGA. PROTECAO CONTRA INSTABILIDADE DO SISTEMA E FALHAS DE SUPRIMENTO.",
            85: "COMUNICA STATUS DE PROTECAO ENTRE TERMINAIS DE LINHAS VIA PORTADORA OU FIO PILOTO. COORDENACAO DE PROTECAO DE ALTA VELOCIDADE ENTRE SUBESTACOES.",
            86: "BLOQUEIA COMANDOS DE TRIP APOS OPERACAO. MANTEM ESTADO DE TRAVAMENTO ATE RESET MANUAL. PROTECAO CONTRA RELIGAMENTOS INTEMPESTIVOS.",
            87: "COMPARA CORRENTES EM AMBOS OS LADOS DE UM EQUIPAMENTO (TRANSFORMADOR, GERADOR, LINHA). DETECTA FALHAS INTERNAS POR DESBALANCO DE CORRENTE DIFERENCIAL.",
            90: "CONTROLA E REGULA PARAMETROS DE SISTEMA COMO TENSAO, POTENCIA OU FREQUENCIA. MANTEM VALORES DENTRO DE FAIXA PRE-AJUSTADA ATRAVES DE ATUACAO CONTINUA.",
            94: "RELE AUXILIAR QUE COMANDA DISPARO FINAL DE DISJUNTORES. AMPLIFICA SINAL DE PROTECAO E OFERECE GARANTIA DE ABERTURA INDEPENDENTE DE OUTRAS PROTECOES (TRIP-FREE)."
        }

        ws.cell(row, 11).value = func_descriptions.get(base_code, "")
        base_code_updated_K.add(base_code)

# Save workbook
wb.save('docs/Pontos Padrao ADMS_v3.xlsx')
print(f"[OK] Todas as descricoes convertidas para MAIUSCULA")
print(f"[OK] Descricoes distintas adicionadas para {len(base_code_updated_K)} codigos base")
print(f"[OK] Suffixos adicionados para diferenciar sinais: F, FA/FB/FC, N, Z1-Z4, D, T, E1-E5, etc")
print(f"[OK] Arquivo salvo: docs/Pontos Padrao ADMS_v3.xlsx")
